export const detailedPets = [
    {
      id: 1,
      name: "Bruno",
      species: "Dog",
      breed: "Indie Mix",
      age: "2 yrs",
      gender: "Male",
      locality: "Hauz Khas, Delhi",
      description:
        "Bruno is a gentle and playful indie mix found near the Hauz Khas metro gate. He is fully house-trained, loves kids, and gets along well with other dogs. He was found malnourished but has recovered beautifully over the past two months. Looking for a patient family who can give him the love he deserves.",
      images: ["/pets/bruno1.jpg", "/pets/bruno2.jpg", "/pets/bruno3.jpg"],
      urgent: false,
      vaccinated: true,
      neutered: true,
      postedBy: { name: "Riya Sharma", avatar: "", locality: "Hauz Khas, Delhi" },
    },
    {
      id: 2,
      name: "Luna",
      species: "Cat",
      breed: "Tabby",
      age: "8 months",
      gender: "Female",
      locality: "Lajpat Nagar, Delhi",
      description:
        "Luna is a sweet tabby kitten rescued from the street outside a market. She was dewormed and vaccinated within a week of rescue. She is shy around strangers at first but warms up very quickly. Loves to curl up in laps and purr. Ideal for a quiet home.",
      images: ["/pets/luna1.jpg", "/pets/luna2.jpg"],
      urgent: true,
      vaccinated: true,
      neutered: false,
      postedBy: { name: "Arjun Mehta", avatar: "", locality: "Lajpat Nagar, Delhi" },
    },
    {
      id: 3,
      name: "Mochi",
      species: "Cat",
      breed: "Orange Tabby",
      age: "1.5 yrs",
      gender: "Male",
      locality: "Vasant Vihar, Delhi",
      description:
        "Mochi is a vocal and playful orange tabby who loves chin scratches and sunny windowsills. He is FIV negative and in perfect health. He does well with other cats. Has been in foster care for 3 months and is ready for his forever home.",
      images: ["/pets/mochi1.jpg", "/pets/mochi2.jpg", "/pets/mochi3.jpg", "/pets/mochi4.jpg"],
      urgent: false,
      vaccinated: true,
      neutered: true,
      postedBy: { name: "Priya Kapoor", avatar: "", locality: "Vasant Vihar, Delhi" },
    },
    {
      id: 4,
      name: "Tommy",
      species: "Dog",
      breed: "Labrador Mix",
      age: "4 yrs",
      gender: "Male",
      locality: "Dwarka, Delhi",
      description:
        "Tommy is a calm and neutered Labrador mix who spent his early years on the street. He has been socialized over the past year and is now friendly with people and children. Knows basic commands. Needs a patient adopter who understands he may take a few weeks to fully settle.",
      images: ["/pets/tommy1.jpg", "/pets/tommy2.jpg", "/pets/tommy3.jpg"],
      urgent: true,
      vaccinated: true,
      neutered: true,
      postedBy: { name: "Karan Verma", avatar: "", locality: "Dwarka, Delhi" },
    },
    {
      id: 5,
      name: "Daisy",
      species: "Cat",
      breed: "Persian Mix",
      age: "9 months",
      gender: "Female",
      locality: "Rohini, Delhi",
      description:
        "Daisy was found injured on the road and was nursed back to full health. She is now a healthy, affectionate, and calm cat who loves to be held. She prefers quiet homes without dogs. Would do well as a single pet or with another calm cat.",
      images: ["/pets/daisy1.jpg", "/pets/daisy2.jpg", "/pets/daisy3.jpg", "/pets/daisy4.jpg", "/pets/daisy5.jpg"],
      urgent: false,
      vaccinated: true,
      neutered: false,
      postedBy: { name: "Riya Sharma", avatar: "", locality: "Rohini, Delhi" },
    },
    {
      id: 6,
      name: "Coco",
      species: "Dog",
      breed: "Spitz Mix",
      age: "3 yrs",
      gender: "Female",
      locality: "Greater Kailash, Delhi",
      description:
        "Coco is an energetic and loving spitz mix who is great with other dogs and children. She knows sit, stay, and paw. Found wandering near GK market with no collar. She has been fostered for 6 weeks and is ready for adoption. Loves outdoor walks.",
      images: ["/pets/coco1.jpg", "/pets/coco2.jpg"],
      urgent: false,
      vaccinated: true,
      neutered: true,
      postedBy: { name: "Neha Tiwari", avatar: "", locality: "Greater Kailash, Delhi" },
    },
  ];