export const samplePets = [
    {
      id: 1,
      name: "Bruno",
      species: "Dog",
      age: "2 yrs",
      locality: "Hauz Khas, Delhi",
      description: "Gentle and playful indie mix found near the metro. House-trained, loves kids and cuddles. Vaccinated.",
      image: "/pets/bruno.jpg",
      postedBy: "Riya S.",
      urgent: false,
    },
    {
      id: 2,
      name: "Luna",
      species: "Cat",
      age: "8 months",
      locality: "Lajpat Nagar, Delhi",
      description: "Sweet tabby kitten rescued from the street. Dewormed and vaccinated. Looking for a cozy forever home.",
      image: "/pets/luna.jpg",
      postedBy: "Arjun M.",
      urgent: true,
    },
    {
      id: 3,
      name: "Mochi",
      species: "Cat",
      age: "1.5 yrs",
      locality: "Vasant Vihar, Delhi",
      description: "Playful orange tabby who loves chin scratches and sunny windowsills. FIV negative, fully healthy.",
      image: "/pets/mochi.jpg",
      postedBy: "Priya K.",
      urgent: false,
    },
    {
      id: 4,
      name: "Tommy",
      species: "Dog",
      age: "4 yrs",
      locality: "Dwarka, Delhi",
      description: "Calm neutered Labrador mix. Former street dog, now friendly and well-socialised. Needs a patient family.",
      image: "/pets/tommy.jpg",
      postedBy: "Karan V.",
      urgent: true,
    },
    {
      id: 5,
      name: "Daisy",
      species: "Cat",
      age: "9 months",
      locality: "Rohini, Delhi",
      description: "Found injured, now fully recovered. Very affectionate and calm. Prefers quiet homes without dogs.",
      image: "/pets/daisy.jpg",
      postedBy: "Riya S.",
      urgent: false,
    },
    {
      id: 6,
      name: "Coco",
      species: "Dog",
      age: "3 yrs",
      locality: "Greater Kailash, Delhi",
      description: "Energetic and loving spitz mix. Great with other dogs. Knows basic commands — sit, stay, paw.",
      image: "/pets/coco.jpg",
      postedBy: "Neha T.",
      urgent: false,
    },
  ];