export const sampleReviews = [
    {
      id: 1,
      name: "Riya Sharma",
      location: "Hauz Khas, Delhi",
      avatar: "",
      petName: "Bruno",
      petType: "Dog",
      rating: 5,
      feeling: "Adopting Bruno was the best decision of my life. The moment he walked into our home, it felt like he had always belonged here. He greets me every morning with so much love — I never knew a rescue dog could fill your heart this completely.",
      date: "March 2025",
    },
    {
      id: 2,
      name: "Arjun Mehta",
      location: "Lajpat Nagar, Delhi",
      avatar: "",
      petName: "Luna",
      petType: "Cat",
      rating: 5,
      feeling: "I was nervous about adopting a stray but Luna made it so easy. She was shy the first week and now she owns the entire apartment. Watching her go from a scared street kitten to a confident little queen has been the most rewarding thing I've witnessed.",
      date: "January 2025",
    },
    {
      id: 3,
      name: "Priya Kapoor",
      location: "Vasant Vihar, Delhi",
      avatar: "",
      petName: "Mochi",
      petType: "Cat",
      rating: 5,
      feeling: "StrayOpt connected me with Mochi's foster within a day. He is the most affectionate cat I have ever met. Coming home to him after a long day at work genuinely changed my mental health for the better. Couldn't imagine life without him now.",
      date: "February 2025",
    },
    {
      id: 4,
      name: "Neha Tiwari",
      location: "Rohini, Delhi",
      avatar: "",
      petName: "Daisy",
      petType: "Cat",
      rating: 4,
      feeling: "Daisy was found injured on the road and nursed back to health before I adopted her. She is the gentlest soul. Knowing I gave a second chance to an animal who had such a rough start makes me emotional every single day. Truly priceless.",
      date: "April 2025",
    },
    {
      id: 5,
      name: "Karan Verma",
      location: "Dwarka, Delhi",
      avatar: "",
      petName: "Tommy",
      petType: "Dog",
      rating: 5,
      feeling: "Tommy was labeled as a street dog that nobody wanted. He is the most loyal and well-behaved dog I have ever owned. My kids adore him. StrayOpt made the whole process so simple — from finding him to contacting the poster. Highly recommend.",
      date: "December 2024",
    },
    {
      id: 6,
      name: "Sneha Iyer",
      location: "Greater Kailash, Delhi",
      avatar: "",
      petName: "Coco",
      petType: "Dog",
      rating: 5,
      feeling: "I never thought I was a dog person until Coco. She brings so much energy and joy into our home. My parents were skeptical at first — now she sleeps between them every night. Giving a stray a home is genuinely one of the most beautiful things you can do.",
      date: "May 2025",
    },
  ];